In [1]:
import pandas as pd

In [116]:
brute_df = pd.read_csv('data/grafo_oportunidades.csv')
brute_df

,id_business_question,business_question,id_data_question,data_question,id_feature,feature,id_dado,dado
0,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,8,lat/long setor censitário/bairro
1,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,9,CNAE
2,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,10,Porte da empresa
3,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,11,Faturamento da empresa
4,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,12,Data de abertura
5,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,13,Data de fechamento
6,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,8,lat/long setor censitário/bairro
7,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,9,CNAE
8,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,10,Porte da empresa
9,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,12,Data de abertura
10,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,13,Data de fechamento
11,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,8,lat/long setor censitário/bairro
12,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,9,CNAE
13,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,10,Porte da empresa
14,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,11,Faturamento da empresa
15,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,12,Data de abertura
16,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,13,Data de fechamento

In [3]:
brute_df.count()

id_business_question    17
business_question       17
id_data_question        17
data_question           17
id_feature              17
feature                 17
id_dado                 17
dado                    17
dtype: int64

In [4]:
brute_df.sum()

id_business_question                                                   17
business_question       Quero ter o negócio X (ex: salão de beleza), q...
id_data_question                                                       34
data_question           Quais negócios de maior sucessoQuais negócios ...
id_feature                                                             34
feature                 Negócios de serviços similaresNegócios de serv...
id_dado                                                                59
dado                    lat/long setor censitário/bairroCNAEPorte da e...
dtype: object

In [5]:
brute_df[brute_df.dado == 'CNAE'].head()

,id_business_question,business_question,id_data_question,data_question,id_feature,feature,id_dado,dado
1,1,"Quero ter o negócio X (ex: salão de beleza), q...",1,Quais negócios de maior sucesso,1,Negócios de serviços similares,2,CNAE
7,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Qual a mortalidade do negócio X?,2,Tempo de abertura e/ou fechamento das empresas,2,CNAE
12,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Quais locais são similares para se ter o negóc...,3,Saturação de negócios similares,2,CNAE

In [168]:
import json

def json_create(data):    
    with open('data/result.json', 'w') as fp:
        json.dump(data, fp)

## Tratamento

In [117]:
brute_df.head(20)

,id_business_question,business_question,id_data_question,data_question,id_feature,feature,id_dado,dado
0,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,8,lat/long setor censitário/bairro
1,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,9,CNAE
2,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,10,Porte da empresa
3,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,11,Faturamento da empresa
4,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,12,Data de abertura
5,1,"Quero ter o negócio X (ex: salão de beleza), q...",2,Quais negócios de maior sucesso,5,Negócios de serviços similares,13,Data de fechamento
6,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,8,lat/long setor censitário/bairro
7,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,9,CNAE
8,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,10,Porte da empresa
9,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,12,Data de abertura
10,1,"Quero ter o negócio X (ex: salão de beleza), q...",3,Qual a mortalidade do negócio X?,6,Tempo de abertura e/ou fechamento das empresas,13,Data de fechamento
11,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,8,lat/long setor censitário/bairro
12,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,9,CNAE
13,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,10,Porte da empresa
14,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,11,Faturamento da empresa
15,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,12,Data de abertura
16,1,"Quero ter o negócio X (ex: salão de beleza), q...",4,Quais locais são similares para se ter o negóc...,7,Saturação de negócios similares,13,Data de fechamento

In [195]:
# Id dos grupos
number_bq = 1
number_dq = 2
number_feature = 3
number_data = 4

In [196]:
group_bq = brute_df[['id_business_question', 'business_question']].drop_duplicates()
group_bq['group'] = number_bq
group_bq.rename(columns={'id_business_question': 'id', 'business_question': 'label'}, inplace=True)

In [197]:
group_bq

   id                                              label  group
0   1  Quero ter o negócio X (ex: salão de beleza), q...      1

In [198]:
group_data_question = brute_df[['id_data_question', 'data_question']].drop_duplicates()
group_data_question['group'] = number_dq
group_data_question.rename(columns={'id_data_question': 'id', 'data_question': 'label'}, inplace=True)

In [199]:
group_data_question

    id                                              label  group
0    2                    Quais negócios de maior sucesso      2
6    3                   Qual a mortalidade do negócio X?      2
11   4  Quais locais são similares para se ter o negóc...      2

In [200]:
group_feature = brute_df[['id_feature', 'feature']].drop_duplicates()
group_feature['group'] = number_feature
group_feature.rename(columns={'id_feature': 'id', 'feature': 'label'}, inplace=True)

In [201]:
group_feature

    id                                           label  group
0    5                  Negócios de serviços similares      3
6    6  Tempo de abertura e/ou fechamento das empresas      3
11   7                 Saturação de negócios similares      3

In [202]:
group_data = brute_df[['id_dado', 'dado']].drop_duplicates()
group_data['group'] = number_data
group_data.rename(columns={'id_dado': 'id', 'dado': 'label'}, inplace=True)

In [203]:
group_data

   id                             label  group
0   8  lat/long setor censitário/bairro      4
1   9                              CNAE      4
2  10                  Porte da empresa      4
3  11            Faturamento da empresa      4
4  12                  Data de abertura      4
5  13                Data de fechamento      4

In [204]:
df_nodes = pd.concat([group_bq, group_data_question, group_feature, group_data], ignore_index=True)

In [205]:
df_nodes

    id                                              label  group
0    1  Quero ter o negócio X (ex: salão de beleza), q...      1
1    2                    Quais negócios de maior sucesso      2
2    3                   Qual a mortalidade do negócio X?      2
3    4  Quais locais são similares para se ter o negóc...      2
4    5                     Negócios de serviços similares      3
5    6     Tempo de abertura e/ou fechamento das empresas      3
6    7                    Saturação de negócios similares      3
7    8                   lat/long setor censitário/bairro      4
8    9                                               CNAE      4
9   10                                   Porte da empresa      4
10  11                             Faturamento da empresa      4
11  12                                   Data de abertura      4
12  13                                 Data de fechamento      4

In [206]:
from_bq_to_dq = brute_df[['id_business_question', 'id_data_question']].drop_duplicates()

In [207]:
from_bq_to_dq.rename(columns={'id_business_question': 'from', 'id_data_question': 'to'}, inplace=True)

In [208]:
from_dq_to_ft = brute_df[['id_data_question', 'id_feature']].drop_duplicates()

In [209]:
from_dq_to_ft.rename(columns={'id_data_question': 'from', 'id_feature': 'to'}, inplace=True)

In [210]:
from_ft_to_data = brute_df[['id_feature', 'id_dado']].drop_duplicates()

In [211]:
from_ft_to_data.rename(columns={'id_feature': 'from', 'id_dado': 'to'}, inplace=True)

In [212]:
df_edges = pd.concat([from_bq_to_dq, from_dq_to_ft, from_ft_to_data])

In [213]:
df_edges['from'] = df_edges['from'].astype(int)
df_edges['to'] = df_edges['to'].astype(int)

df_nodes['id'] = df_nodes['id'].astype(int)

Fiz isso para o pandas se virar convertendo os int64 em int, porque a lib json não consegue converter em json in64

In [214]:
node_list = df_nodes.to_json(orient='records', force_ascii=False)

In [215]:
edges_list = df_edges.to_json(orient='records', force_ascii=False)

In [216]:
result = {'nodes': json.loads(node_list), 'edges': json.loads(edges_list)}

In [217]:
result

{'nodes': [{'id': 1,
   'label': 'Quero ter o negócio X (ex: salão de beleza), qual o melhor local para abrir?',
   'group': 1},
  {'id': 2, 'label': 'Quais negócios de maior sucesso', 'group': 2},
  {'id': 3, 'label': 'Qual a mortalidade do negócio X?', 'group': 2},
  {'id': 4,
   'label': 'Quais locais são similares para se ter o negócio X?',
   'group': 2},
  {'id': 5, 'label': 'Negócios de serviços similares', 'group': 3},
  {'id': 6,
   'label': 'Tempo de abertura e/ou fechamento das empresas',
   'group': 3},
  {'id': 7, 'label': 'Saturação de negócios similares', 'group': 3},
  {'id': 8, 'label': 'lat/long setor censitário/bairro', 'group': 4},
  {'id': 9, 'label': 'CNAE', 'group': 4},
  {'id': 10, 'label': 'Porte da empresa', 'group': 4},
  {'id': 11, 'label': 'Faturamento da empresa', 'group': 4},
  {'id': 12, 'label': 'Data de abertura', 'group': 4},
  {'id': 13, 'label': 'Data de fechamento', 'group': 4}],
 'edges': [{'from': 1, 'to': 2},
  {'from': 1, 'to': 3},
  {'from': 1, 'to': 4},
  {'from': 2, 'to': 5},
  {'from': 3, 'to': 6},
  {'from': 4, 'to': 7},
  {'from': 5, 'to': 8},
  {'from': 5, 'to': 9},
  {'from': 5, 'to': 10},
  {'from': 5, 'to': 11},
  {'from': 5, 'to': 12},
  {'from': 5, 'to': 13},
  {'from': 6, 'to': 8},
  {'from': 6, 'to': 9},
  {'from': 6, 'to': 10},
  {'from': 6, 'to': 12},
  {'from': 6, 'to': 13},
  {'from': 7, 'to': 8},
  {'from': 7, 'to': 9},
  {'from': 7, 'to': 10},
  {'from': 7, 'to': 11},
  {'from': 7, 'to': 12},
  {'from': 7, 'to': 13}]}

In [218]:
json_create(result)

In [219]:
result

{'nodes': [{'id': 1,
   'label': 'Quero ter o negócio X (ex: salão de beleza), qual o melhor local para abrir?',
   'group': 1},
  {'id': 2, 'label': 'Quais negócios de maior sucesso', 'group': 2},
  {'id': 3, 'label': 'Qual a mortalidade do negócio X?', 'group': 2},
  {'id': 4,
   'label': 'Quais locais são similares para se ter o negócio X?',
   'group': 2},
  {'id': 5, 'label': 'Negócios de serviços similares', 'group': 3},
  {'id': 6,
   'label': 'Tempo de abertura e/ou fechamento das empresas',
   'group': 3},
  {'id': 7, 'label': 'Saturação de negócios similares', 'group': 3},
  {'id': 8, 'label': 'lat/long setor censitário/bairro', 'group': 4},
  {'id': 9, 'label': 'CNAE', 'group': 4},
  {'id': 10, 'label': 'Porte da empresa', 'group': 4},
  {'id': 11, 'label': 'Faturamento da empresa', 'group': 4},
  {'id': 12, 'label': 'Data de abertura', 'group': 4},
  {'id': 13, 'label': 'Data de fechamento', 'group': 4}],
 'edges': [{'from': 1, 'to': 2},
  {'from': 1, 'to': 3},
  {'from': 1, 'to': 4},
  {'from': 2, 'to': 5},
  {'from': 3, 'to': 6},
  {'from': 4, 'to': 7},
  {'from': 5, 'to': 8},
  {'from': 5, 'to': 9},
  {'from': 5, 'to': 10},
  {'from': 5, 'to': 11},
  {'from': 5, 'to': 12},
  {'from': 5, 'to': 13},
  {'from': 6, 'to': 8},
  {'from': 6, 'to': 9},
  {'from': 6, 'to': 10},
  {'from': 6, 'to': 12},
  {'from': 6, 'to': 13},
  {'from': 7, 'to': 8},
  {'from': 7, 'to': 9},
  {'from': 7, 'to': 10},
  {'from': 7, 'to': 11},
  {'from': 7, 'to': 12},
  {'from': 7, 'to': 13}]}